# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200, verbose_name='Nome do Ativo')),
                ('asset_code', models.CharField(max_length=200, unique=True, verbose_name='Código do Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_price', models.FloatField(verbose_name='preço do dia')),
                ('date', models.DateTimeField(default=datetime.date(1000, 1, 1))),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('CP', 'Compra'), ('VD', 'Venda')], default='CP', max_length=20)),
                ('unit_price', models.FloatField(verbose_name='Valor unitário da Transação')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('transaction_date', models.DateTimeField(default=datetime.date(1000, 1, 1))),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Asset')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('asset', 'unit_price', 'nature', 'quantity', 'transaction_date')]),
        ),
    ]
