# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200, unique=True, verbose_name='Nome do Ativo')),
                ('asset_code', models.CharField(max_length=200, unique=True, verbose_name='Código do Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpe', models.CharField(choices=[('TR', 'Transactional'), ('DV', 'Daily Value')], default='DV', max_length=20)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date(2015, 9, 29), unique=True)),
                ('weekday', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=20)),
                ('month', models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Ago'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('CP', 'Compra'), ('VD', 'Venda')], default='CP', max_length=20)),
                ('price', models.FloatField(verbose_name='Valor Transação')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('nature', 'price', 'quantity')]),
        ),
        migrations.AddField(
            model_name='assetsanalytics',
            name='dateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Date'),
        ),
        migrations.AddField(
            model_name='assetsanalytics',
            name='transactionId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='assetsanalytics',
            unique_together=set([('assetId', 'dateId', 'transactionId', 'tpe')]),
        ),
    ]
