# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(default=datetime.date(1000, 1, 1), unique=True),
        ),
    ]
