# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180130_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 21, 29, 9, 360516)),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nature',
            field=models.CharField(choices=[('CP', 'Compra'), ('VD', 'Venda')], default='CP', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Código do Ativo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome do Ativo'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('asset', 'price', 'nature', 'quantity', 'date')]),
        ),
    ]
