# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180130_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpe', models.CharField(choices=[('TR', 'Transactional'), ('DV', 'Daily Value')], default='DV', max_length=20)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 2, 14, 21, 50, 22, 468029), unique=True)),
                ('weekday', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=20)),
                ('month', models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Ago'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('nature', 'price', 'quantity')]),
        ),
        migrations.AddField(
            model_name='assetsanalytics',
            name='dateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Date'),
        ),
        migrations.AddField(
            model_name='assetsanalytics',
            name='transactionId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='assetsanalytics',
            unique_together=set([('assetId', 'dateId', 'transactionId', 'tpe')]),
        ),
    ]
