# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180214_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(default='1000-01-01', unique=True),
        ),
    ]
