# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180214_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 22, 1, 50, 270079), unique=True),
        ),
    ]
