# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180214_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(default='2009-07-24', unique=True),
        ),
    ]
