# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 22:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180214_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(default=datetime.date(2015, 9, 29), unique=True),
        ),
    ]
